learn troubleshoot
brainchildservices/Learn-Troubleshooting pull request #1
Opened 2021-07-15 12:51 UTC by SijoGeorge7012

![image](https://user-images.githubusercontent.com/78071547/125790946-58a7f84d-a39b-42d2-98c1-d33107fa9dcb.png)
![image](https://user-images.githubusercontent.com/78071547/125790973-cee50d99-a277-4214-94ab-5473e2ebfec9.png)
![image](https://user-images.githubusercontent.com/78071547/125791012-b6565692-2d7c-4bbf-b75d-5f86bab89b20.png)

2021-07-16 13:31 UTC, wandercode requested changes

2021-07-16 13:31 UTC, wandercode commented on 001troubleshooting.html
> +                    <img src="image/image27.png" alt="">
include the check by text input part on previous slide. 
only tasks should reamin in this slide.

2021-07-16 13:31 UTC, wandercode commented on 001troubleshooting.html
> +                    <img src="image/image27.png" alt="">
include the check by text input part on previous slide. 
only tasks should remain in this slide.

2021-07-16 13:31 UTC, wandercode commented on 001troubleshooting.html
> +                    <img src="image/image27.png" alt="">
include the check by text input part on previous slide. 
only tasks should remain in this slide.

2021-07-16 13:35 UTC, wandercode requested changes

2021-07-16 13:35 UTC, wandercode commented on 001troubleshooting.html
> +                    <p id="para">Please Clone the <a href="https://github.com/brainchildservices/Troubleshooting" target="_blank">Troubleshooting Reposittory</a>  to your Local Storage, to Continue
please make the link to open on another tab

2021-07-19 06:56 UTC, VishnuKulakkattu approved these changes

2021-07-19 07:52 UTC, VishnuKulakkattu requested changes

2021-07-19 07:52 UTC, VishnuKulakkattu commented on 001troubleshooting.html
> +                    <p id="label2">* Check By File Upload:- You can upload a file from your Local Drive and check</p>
Kindly arrange the Points & Screenshot in a single slide

2021-07-20 05:05 UTC, merged