new slide TS025AID
brainchildservices/Learn-Troubleshooting pull request #2
Opened 2021-07-15 13:14 UTC by Anand-Madhu123

![t2](https://user-images.githubusercontent.com/82358381/125793854-73bc98b2-50cb-4aec-86f2-fc8c1133e642.JPG)
![t2](https://user-images.githubusercontent.com/82358381/125794009-04476c55-73d3-489b-86a4-b20517ae2d05.JPG)
![t3](https://user-images.githubusercontent.com/82358381/125794021-fd4efd42-6c6e-40f0-9253-d10078756a8d.JPG)
![t5](https://user-images.githubusercontent.com/82358381/125794025-41d5e5bc-ab10-4675-a0a0-4ce6aecf3147.JPG)
![t6](https://user-images.githubusercontent.com/82358381/125794035-cf726f7d-ca17-489b-b40f-4a5f719886d6.JPG)
![t7](https://user-images.githubusercontent.com/82358381/125794051-a05b131a-c1e3-49e9-aa38-056b267d3dc8.JPG)
![t11](https://user-images.githubusercontent.com/82358381/125794059-0857fc1d-5707-4c27-b5f0-d21999b0d26a.JPG)
![10](https://user-images.githubusercontent.com/82358381/125794079-667aa0f4-dfde-449a-9d73-d31c9fe76601.JPG)

2021-07-19 07:56 UTC, VishnuKulakkattu requested changes

2021-07-19 07:56 UTC, VishnuKulakkattu commented on troubleshoot.html
> +					<h6>Please Clone the Troubleshooting Repository to your Local Storage, to Continue</h6>
Add Troubleshooting Repo Link

2021-07-19 09:19 UTC, Anand-Madhu123 commented on troubleshoot.html
> +					<h6>Please Clone the Troubleshooting Repository to your Local Storage, to Continue</h6>
done

2021-07-19 09:22 UTC, VishnuKulakkattu approved these changes

2021-07-20 04:53 UTC, wandercode approved these changes

2021-07-20 04:58 UTC, merged